# Makefile
# --------
#
# Build targets:
#   make full        → cv-full.pdf         (complete academic CV)
#   make full-public → cv-full-public.pdf  (full minus mentorship section)
#   make industry    → cv-industry.pdf     (selected pubs, lean)
#   make speaking    → cv-speaking.pdf     (talks + selected pubs)
#   make resume      → resume.pdf          (one-page industry resume; uses resume.tex)
#   make all         → builds all five outputs
#   make pdf         → compile current cv-preset.tex → cv.pdf (internal)
#   make clean       → remove LaTeX build artifacts
#
# cv-preset.tex is auto-generated by the preset targets.
# If it doesn't exist (fresh clone), it defaults to config/full.tex.
#
# resume.pdf has its own pipeline — it builds from resume.tex + awesome-cv-resume.cls
# and does NOT go through cv-preset.tex or biber. Keep both files in sync with the
# rest of the CV when content changes (see resume.tex header for guidance).

.PHONY: all full full-public industry speaking resume pdf clean fetch fetch-dry dedup test validate audit-authors setup check-deps status

# Build all outputs
all: full full-public industry speaking resume

# Individual preset targets
full:
	cp config/full.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-full.pdf
	@echo "→ cv-full.pdf"

full-public:
	cp config/full-public.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-full-public.pdf
	cp cv-full-public.pdf shabnam-hakimi-cv.pdf
	@echo "→ cv-full-public.pdf (also published as shabnam-hakimi-cv.pdf)"

industry:
	cp config/industry.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-industry.pdf
	@echo "→ cv-industry.pdf"

speaking:
	cp config/speaking.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-speaking.pdf
	@echo "→ cv-speaking.pdf"

# One-page industry resume — standalone pipeline (no biber, no cv-preset.tex).
# Two xelatex passes are sufficient since resume.tex has no bibliography.
resume:
	xelatex -interaction=nonstopmode resume.tex
	xelatex -interaction=nonstopmode resume.tex
	@echo "→ resume.pdf"

# Core LaTeX compile (used internally by preset targets)
# cv-preset.tex must exist before calling this directly.
cv-preset.tex:
	@echo "No cv-preset.tex found — using default (full)."
	cp config/full.tex cv-preset.tex

pdf: cv-preset.tex
	xelatex cv.tex
	biber cv
	xelatex cv.tex
	xelatex cv.tex

clean:
	rm -f cv.aux cv.bbl cv.bcf cv.blg cv.log cv.out cv.run.xml cv.toc cvbibcounts.tex
	rm -f resume.aux resume.log resume.out
	rm -f cv-full.pdf cv-full-public.pdf cv-industry.pdf cv-speaking.pdf cv.pdf shabnam-hakimi-cv.pdf resume.pdf

fetch:
	python scripts/update_refs.py

fetch-dry:
	python scripts/update_refs.py --dry-run

dedup:
	python scripts/update_refs.py --dedup-only

test:
	python3 -m pytest tests/ -v

validate:
	python3 scripts/validate_bib.py

# Checks author lists against Crossref (publisher DOIs) and DataCite
# (arXiv DOIs). Hits the network, so it is not part of `validate`.
# Worth running after any fetch, and after hand-editing an author list.
audit-authors:
	python3 scripts/audit_authors.py

# First-run setup. Installs `requests` + `bibtexparser` (required for
# fetchers and dedup) and `pytest` (required for `make test`).
setup:
	python3 -m pip install -r requirements-dev.txt

# Working-tree and upstream state for this repo and the research corpus.
#
# Every git call goes through `git -C <dir>` rather than `cd <dir> && git`.
# A cd-chain reports whatever directory the shell happens to be sitting in,
# so one missing cd makes it print another repo's state under this repo's
# heading -- wrong, and indistinguishable from right.
#
# cv-preset.tex is rewritten by every preset target, so it shows as modified
# after any build. That is expected and is called out below rather than
# filtered, so the count always matches what git actually reports.
CORPUS_DIR ?= $(HOME)/projects/research-corpus

status:
	@for d in "$(CURDIR)" "$(CORPUS_DIR)"; do \
	  name=$$(basename "$$d"); \
	  if [ ! -e "$$d/.git" ]; then \
	    printf '%-18s not a git repo (%s)\n' "$$name" "$$d"; continue; \
	  fi; \
	  branch=$$(git -C "$$d" rev-parse --abbrev-ref HEAD 2>/dev/null); \
	  head=$$(git -C "$$d" log -1 --format=%h 2>/dev/null); \
	  dirty=$$(git -C "$$d" status --porcelain | wc -l | tr -d ' '); \
	  ahead=$$(git -C "$$d" rev-list --count '@{u}..HEAD' 2>/dev/null || echo '-'); \
	  behind=$$(git -C "$$d" rev-list --count 'HEAD..@{u}' 2>/dev/null || echo '-'); \
	  printf '%-18s %-6s %-9s dirty:%-4s ahead:%-4s behind:%s\n' \
	    "$$name" "$$branch" "$$head" "$$dirty" "$$ahead" "$$behind"; \
	  git -C "$$d" status --porcelain | sed 's/^/                     /'; \
	done
	@echo
	@echo "(cv-preset.tex modified after a build is expected, not dirt.)"

# Preflight: verify required Python deps are importable. Prints an
# actionable hint instead of a bare ImportError traceback.
check-deps:
	@python3 -c "import requests, bibtexparser" 2>/dev/null && \
	  echo "Python deps OK." || \
	  (echo "Missing Python deps. Run:  make setup" && exit 1)
