# Makefile
# --------
#
# Build targets:
#   make full        → cv-full.pdf         (complete academic CV)
#   make full-public → cv-full-public.pdf  (full minus mentorship section)
#   make industry    → cv-industry.pdf     (selected pubs, lean)
#   make speaking    → cv-speaking.pdf     (talks + selected pubs)
#   make all         → builds all four presets
#   make pdf         → compile current cv-preset.tex → cv.pdf (internal)
#   make clean       → remove LaTeX build artifacts
#
# cv-preset.tex is auto-generated by the preset targets.
# If it doesn't exist (fresh clone), it defaults to config/full.tex.

.PHONY: all full full-public industry speaking pdf clean fetch fetch-dry dedup test validate setup check-deps

# Build all presets
all: full full-public industry speaking

# Individual preset targets
full:
	cp config/full.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-full.pdf
	@echo "→ cv-full.pdf"

full-public:
	cp config/full-public.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-full-public.pdf
	cp cv-full-public.pdf shabnam-hakimi-cv.pdf
	@echo "→ cv-full-public.pdf (also published as shabnam-hakimi-cv.pdf)"

industry:
	cp config/industry.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-industry.pdf
	@echo "→ cv-industry.pdf"

speaking:
	cp config/speaking.tex cv-preset.tex
	$(MAKE) pdf
	mv cv.pdf cv-speaking.pdf
	@echo "→ cv-speaking.pdf"

# Core LaTeX compile (used internally by preset targets)
# cv-preset.tex must exist before calling this directly.
cv-preset.tex:
	@echo "No cv-preset.tex found — using default (full)."
	cp config/full.tex cv-preset.tex

pdf: cv-preset.tex
	xelatex cv.tex
	biber cv
	xelatex cv.tex
	xelatex cv.tex

clean:
	rm -f cv.aux cv.bbl cv.bcf cv.blg cv.log cv.out cv.run.xml cv.toc cvbibcounts.tex
	rm -f cv-full.pdf cv-full-public.pdf cv-industry.pdf cv-speaking.pdf cv.pdf shabnam-hakimi-cv.pdf

fetch:
	python scripts/update_refs.py

fetch-dry:
	python scripts/update_refs.py --dry-run

dedup:
	python scripts/update_refs.py --dedup-only

test:
	python3 -m pytest tests/ -v

validate:
	python3 scripts/validate_bib.py

# First-run setup. Installs `requests` + `bibtexparser` (required for
# fetchers and dedup) and `pytest` (required for `make test`).
setup:
	python3 -m pip install -r requirements-dev.txt

# Preflight: verify required Python deps are importable. Prints an
# actionable hint instead of a bare ImportError traceback.
check-deps:
	@python3 -c "import requests, bibtexparser" 2>/dev/null && \
	  echo "Python deps OK." || \
	  (echo "Missing Python deps. Run:  make setup" && exit 1)
